### PR TITLE
Project Initiated

### PR DESCRIPTION
**Pull request by aurora-0025**
Made the discord bot with command, event and slash command handler

### CODE REVIEW

**Comment by aurora-0025** [comment]
referencing #1

**Comment by AnkushSinghGandhi** [comment]
@aurora-0025 Thanks for the PR! Please give us some time to review it.

**Review by unnati914 — APPROVED** [review]
Awesome work @aurora-0025!

**Review by AnkushSinghGandhi — APPROVED** [review]
Great work @aurora-0025

**Pull request merged**
